spring:
  application:
    name: to_do_list
  datasource:
    url: jdbc:h2:mem:todo-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080



